### ISSUE TITLE
Nested(:method) raises: undefined method `call' for nil:NilClass

### ISSUE THREAD

**Issue by emaglio** [trailblazer/trailblazer-macro#17]
Seems like using `Nested` with builder is broken at the moment.

Activity:
```ruby
class MyOperation < Trailblazer::Operation
    step Nested(:parse)

    def parse(_options, message:, **)
      if message.quick_reply?
        ReplyQuickly
      else
        LongBoringReply
      end
    end
  end
```

Error stack trace:
```
  1) MyOperation when postback 
     Failure/Error: let(:result) { described_class.call(message: incoming) }
     
     NoMethodError:
       undefined method `call' for nil:NilClass
       Did you mean?  caller
     # ./.bundle/ruby/2.3.0/gems/trailblazer-context-0.1.2/lib/trailblazer/option.rb:74:in `call!'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-context-0.1.2/lib/trailblazer/option.rb:31:in `evaluate_callable'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-context-0.1.2/lib/trailblazer/option.rb:16:in `block in build'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/task_builder.rb:27:in `call'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/task_wrap/call_task.rb:11:in `call_task'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/task_wrap/pipeline.rb:12:in `call'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/task_wrap/pipeline.rb:12:in `block in call'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/task_wrap/pipeline.rb:12:in `each'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/task_wrap/pipeline.rb:12:in `call'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/task_wrap/runner.rb:23:in `call'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/circuit.rb:45:in `block in call'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/circuit.rb:44:in `loop'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/circuit.rb:44:in `call'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity.rb:11:in `call'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/task_wrap/call_task.rb:11:in `call_task'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/task_wrap/pipeline.rb:12:in `call'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/task_wrap/pipeline.rb:12:in `block in call'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/task_wrap/pipeline.rb:12:in `each'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/task_wrap/pipeline.rb:12:in `call'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/task_wrap/runner.rb:23:in `call'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/task_wrap.rb:24:in `invoke'
     # ./.bundle/ruby/2.3.0/bundler/gems/trailblazer-operation-7c92a5e52790/lib/trailblazer/operation/public_call.rb:27:in `call_with_public_interface'
     # ./.bundle/ruby/2.3.0/bundler/gems/trailblazer-operation-7c92a5e52790/lib/trailblazer/operation/public_call.rb:18:in `call'
     # ./spec/app/concepts/my_operation_spec.rb:17:in `block (2 levels) in <top (required)>'
```

**Comment by emaglio** [comment]
Seems like this is fixed but now `step Subprocess(MyOtherOperation)` raises the same error:
```
     NoMethodError:
       undefined method `call' for nil:NilClass
       Did you mean?  caller
     # ./.bundle/ruby/2.3.0/gems/trailblazer-context-0.1.2/lib/trailblazer/option.rb:74:in `call!'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-context-0.1.2/lib/trailblazer/option.rb:31:in `evaluate_callable'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-context-0.1.2/lib/trailblazer/option.rb:16:in `block in build'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-dsl-linear-0.1.3/lib/trailblazer/activity/dsl/linear/variable_mapping.rb:77:in `call'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/task_wrap/variable_mapping.rb:81:in `call'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/task_wrap/pipeline.rb:12:in `block in call'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/task_wrap/pipeline.rb:12:in `each'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/task_wrap/pipeline.rb:12:in `call'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/task_wrap/runner.rb:23:in `call'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/circuit.rb:45:in `block in call'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/circuit.rb:44:in `loop'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/circuit.rb:44:in `call'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity.rb:11:in `call'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/task_wrap/call_task.rb:11:in `call_task'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/task_wrap/pipeline.rb:12:in `call'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/task_wrap/pipeline.rb:12:in `block in call'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/task_wrap/pipeline.rb:12:in `each'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/task_wrap/pipeline.rb:12:in `call'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/task_wrap/runner.rb:23:in `call'
     # ./.bundle/ruby/2.3.0/gems/trailblazer-activity-0.8.0/lib/trailblazer/activity/task_wrap.rb:24:in `invoke'
     # ./.bundle/ruby/2.3.0/bundler/gems/trailblazer-operation-31679158b0ee/lib/trailblazer/operation/public_call.rb:28:in `call_with_public_interface'
     # ./.bundle/ruby/2.3.0/bundler/gems/trailblazer-operation-31679158b0ee/lib/trailblazer/operation/public_call.rb:19:in `call'
     # ./spec/app/concepts/purchase/charge_stripe/subscription_spec.rb:19:in `block (2 levels) in <top (required)>'
```

**Comment by apotonick** [comment]
Could you show me `MyOtherOperation`? It looks like this is a different error coming from `:input` or `:output` (I see `variable_mapping.rb`).

**Comment by yogeshjain999** [comment]
I couldn't reproduce it, is it still happening ?

**Comment by emaglio** [comment]
To be honest I have no idea. Let's close this and we will see if someone else will raise this again
